---
kind: pipeline
type: kubernetes
name: staging

trigger:
  branch:
    - staging

# replace mobile-edge-in-car-voice-assistant with your demo name for eg.: financial-news-vector-search
steps:
  - name: publish-backend
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com ## keep same for all demos < - aws ecr registry used to store docker image
      repo: industrysolutions/mobile-edge-in-car-voice-assistant-backend ## NEED TO CHANGE - based on your demo name for eg.: financial-news-vector-search
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      dockerfile: Dockerfile.backend
      access_key:
        from_secret: ecr_access_key ## set in drone web ui
      secret_key:
        from_secret: ecr_secret_key ## set in drone web ui
    when:
      event:
        - push

  - name: publish-frontend
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: industrysolutions/mobile-edge-in-car-voice-assistant-frontend ## NEED TO CHANGE - based on your demo name for eg.: financial-news-vector-search
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      # build_args:
      #   - NEXT_BACKEND_URL: http://mobile-edge-in-car-voice-assistant-backend-web-app:80
      dockerfile: Dockerfile.frontend
      access_key:
        from_secret: ecr_access_key ## set in drone web ui
      secret_key:
        from_secret: ecr_secret_key ## set in drone web ui
    when:
      event:
        - push

  - name: deploy-backend-staging
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: industrysolutions
      release: mobile-edge-in-car-voice-assistant-backend ## NEED TO CHANGE - based on your demo name for eg.: financial-news-vector-search
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/mobile-edge-in-car-voice-assistant-backend" ## NEED TO CHANGE replace mobile-edge-in-car-voice-assistant with your backend pod name from above
        - "ingress.enabled=true"
        - "ingress.hosts[0]=mobile-edge-in-car-voice-assistant-backend.industrysolutions.staging.corp.mongodb.com" ## NEED TO CHANGE replace mobile-edge-in-car-voice-assistant with your demo name for eg.: financial-news-vector-search
        - "mesh.enabled=true"
        - "resources.limits.cpu=1000m"
        - "resources.limits.memory=1024Mi"
        - "resources.requests.cpu=250m"
        - "resources.requests.memory=256Mi"
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token ## set in drone web ui
      values_files: [ "environment/staging.yaml" ]
    when:
      event:
        - push

  - name: deploy-frontend-staging
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: industrysolutions
      release: mobile-edge-in-car-voice-assistant-frontend
      values:
        - "image.tag=git-${DRONE_COMMIT_SHA:0:7}"
        - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/mobile-edge-in-car-voice-assistant-frontend" ## NEED TO CHANGE replace mobile-edge-in-car-voice-assistant
        - "ingress.enabled=true"
        - "ingress.hosts[0]=mobile-edge-in-car-voice-assistant-frontend.industrysolutions.staging.corp.mongodb.com" ## NEED TO CHANGE replace mobile-edge-in-car-voice-assistant with your demo name for eg.: financial-news-vector-search
        - "mesh.enabled=true"
        - "resources.limits.cpu=1000m"
        - "resources.limits.memory=1024Mi"
        - "resources.requests.cpu=250m"
        - "resources.requests.memory=256Mi"
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token ## set in drone web ui
      values_files: [ "environment/staging.yaml" ]
    when:
      event:
        - push

---
# kind: pipeline
# type: kubernetes
# name: production

# trigger:
#   branch:
#     - main  # or master, depending on your main branch name

# steps:
#   - name: publish-backend-prod
#     image: plugins/kaniko-ecr
#     settings:
#       create_repository: true
#       registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com # keep same for all demos < - aws ecr registry used to store docker image
#       repo: industrysolutions/mobile-edge-in-car-voice-assistant-backend-prod ## NEED TO CHANGE - based on your demo name for eg.: financial-news-vector-search-backend-prod
#       tags:
#         - git-${DRONE_COMMIT_SHA:0:7}-prod
#         - prod-latest
#       dockerfile: Dockerfile.backend
#       access_key:
#         from_secret: ecr_access_key
#       secret_key:
#         from_secret: ecr_secret_key
#     when:
#       event:
#         - push

#   - name: publish-frontend-prod
#     image: plugins/kaniko-ecr
#     settings:
#       create_repository: true
#       registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
#       repo: industrysolutions/mobile-edge-in-car-voice-assistant-frontend-prod ## NEED TO CHANGE - based on your demo name for eg.: financial-news-vector-search-frontend
#       tags:
#         - git-${DRONE_COMMIT_SHA:0:7}-prod
#         - prod-latest
#       dockerfile: Dockerfile.frontend
#       access_key:
#         from_secret: ecr_access_key
#       secret_key:
#         from_secret: ecr_secret_key
#     when:
#       event:
#         - push

#   - name: deploy-backend-production
#     image: public.ecr.aws/kanopy/drone-helm:v3
#     settings:
#       chart: mongodb/web-app
#       chart_version: 4.25.0
#       add_repos: [mongodb=https://10gen.github.io/helm-charts]
#       namespace: industrysolutions
#       release: mobile-edge-in-car-voice-assistant-backend-prod ## NEED TO CHANGE - based on your demo name for eg.: financial-news-vector-search-backend-prod
#       values:
#         - "image.tag=git-${DRONE_COMMIT_SHA:0:7}-prod"
#         - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/mobile-edge-in-car-voice-assistant-backend-prod" ## NEED TO CHANGE replace mobile-edge-in-car-voice-assistant with your backend pod name from above
#         - "ingress.enabled=true"
#         - "ingress.hosts[0]=mobile-edge-in-car-voice-assistant-backend.industrysolutions.prod.corp.mongodb.com"
#         - "mesh.enabled=true"
#         - "resources.limits.cpu=1000m"
#         - "resources.limits.memory=1024Mi"
#         - "resources.requests.cpu=250m"
#         - "resources.requests.memory=256Mi"
#       api_server: https://api.prod.corp.mongodb.com
#       kubernetes_token:
#         from_secret: production_kubernetes_token
#       values_files: [ "environment/production.yaml" ]
#     when:
#       event:
#         - push

#   - name: deploy-frontend-production
#     image: public.ecr.aws/kanopy/drone-helm:v3
#     settings:
#       chart: mongodb/web-app
#       chart_version: 4.25.0
#       add_repos: [mongodb=https://10gen.github.io/helm-charts]
#       namespace: industrysolutions
#       release: mobile-edge-in-car-voice-assistant-frontend-prod
#       values:
#         - "image.tag=git-${DRONE_COMMIT_SHA:0:7}-prod"
#         - "image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/mobile-edge-in-car-voice-assistant-frontend-prod"
#         - "ingress.enabled=true"
#         - "ingress.hosts[0]=mobile-edge-in-car-voice-assistant-frontend.industrysolutions.prod.corp.mongodb.com"
#         - "mesh.enabled=true"
#         - "resources.limits.cpu=1000m"
#         - "resources.limits.memory=1024Mi"
#         - "resources.requests.cpu=250m"
#         - "resources.requests.memory=256Mi"
#       api_server: https://api.prod.corp.mongodb.com
#       kubernetes_token:
#         from_secret: production_kubernetes_token
#       values_files: [ "environment/production.yaml" ]
#     when:
#       event:
#         - push