env:
  NODE_ENV: staging
  # AWS region for IRSA (no credentials needed)
  AWS_REGION: us-east-1
  # Backend API URL for frontend to connect to backend health check - get <service-name> using kubectl get services
  BACKEND_URL: http://mobile-edge-in-car-voice-assistant-backend-web-app:80   # or http://localhost:8000 if multicontainer pod is setup and backend is running on 8000
  #COLLECTION_NAME: test-collection
  
  # GCP Workload Identity Configuration
  # GOOGLE_APPLICATION_CREDENTIALS: /etc/gcp/credential-configuration.json
  # GCP_PROJECT_ID: manufacturing-project-425012
  # GCP_LOCATION: us-central1

## Single Pod Containers
envSecrets:
  # MongoDB Configuration
  MONGODB_URI: mobile-edge-in-car-voice-assistant-staging
  DATABASE_NAME: mobile-edge-in-car-voice-assistant-staging  
  AGENT_MODEL_ID: mobile-edge-in-car-voice-assistant-staging

## should be used in case of multiple sidecar containers
# sidecarContainers:
#   - name: backend
#     image: 275662791714.dkr.ecr.us-east-1.amazonaws.com/mobile-edge-in-car-voice-assistant-backend:latest
#     env:
#       # MongoDB connection (from Kubernetes secret)
#       - name: MONGODB_URI
#         valueFrom:
#           secretKeyRef:
#             name: session-temp-kanopy
#             key: MONGODB_URI

#       - name: DATABASE_NAME
#         valueFrom:
#           secretKeyRef:
#             name: session-temp-kanopy
#             key: DATABASE_NAME

#       # Voyage AI API Key (embeddings)
#       - name: VOYAGE_API_KEY
#         valueFrom:
#           secretKeyRef:
#             name: session-temp-kanopy
#             key: VOYAGE_API_KEY
    
## ----------------------------- Cloud Specific Configurations -----------------------------

# Add IRSA configuration here, role here gives access to bedrock, s3, aws secrets manager
serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-staging-cicd-irsa"

## For GCP this, example setup here is for manufacturing

# serviceAccount:
#   enabled: true
#   annotations:
#     iam.gke.io/gcp-service-account: "manufacturing-kanopy-sa@manufacturing-project-425012.iam.gserviceaccount.com"


# # Mount GCP credential config and service account token
# extraVolumes:
#  - name: gcp-creds
#    configMap:
#      name: gcp-wif-config
#  - name: gcp-token
#    projected:
#      sources:
#      - serviceAccountToken:
#          path: token
#          expirationSeconds: 3600
#          audience: "//iam.googleapis.com/projects/362614368442/locations/global/workloadIdentityPools/kanopy-manufacturing-wif-pool/providers/kanopy-manufacturing-provider"


# extraVolumeMounts:
#  - name: gcp-creds
#    mountPath: /etc/gcp
#    readOnly: true
#  - name: gcp-token
#    mountPath: /var/run/service-account
#    readOnly: true